feat: 관리자 로그인 API 구현
Nexters/nexters-admin-server pull request #10
Opened 2023-02-09 15:15 UTC by bugoverdose

간단하게 어드민 로그인을 구현해보았습니다.

- `POST /api/auth/login/admin`

### 공유사항

1. 일단은 도메인 테스트만 만들었는데, 이 PR이 머지되기 전에 테스트 코드 컨벤션이 충분히 확정되었다 싶으면 바로 작성할께요.
2. MemberController 쪽 PR이 머지된 이후에 AuthController에 일반 회원 로그인도 넣읍시다.

2023-02-09 15:53 UTC, kth990303 approved these changes
지금도 괜찮긴 한데 몇 가지 코멘트 남겨봤습니다.
수고하셨어요!

2023-02-09 15:53 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
> +        return this.password.value == password.value
테스트 코드의 중복(관리자, 일반회원에서의 검증 테스트)이 발생할 것 같은데`Password` VO한테 메시지를 던지도록 변경해보는 것도 괜찮겠네요. 패스워드가 일치하는지 검증의 책임은 패스워드한테 맡겨도 괜찮을 듯해요

```suggestion
        return this.password.isSamePassword(password)
```

2023-02-09 15:53 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
> +        val password: Password
이 부분 고치기로 했으니, 아예 지금 바꿔버리죠!
```suggestion
        val password: String
```

2023-02-09 15:53 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
> +        var lastAccessTime: LocalDateTime? = null,
trailing comma 추가 👍 

근데 생각해보니까 얘 null 대신 LocalDateTime이어도 될 것 같기도 한데 왜 null로 하자고 했었죠 우리..?ㅋㅋㅋㅋ

2023-02-09 15:53 UTC, kth990303 commented on src/test/kotlin/nexters/admin/domain/user/administrator/AdministratorTest.kt
> +        admin.lastAccessTime!! shouldBeGreaterThan prevAccessTime
개인적으로 `!!`를 최대한 지양하자는 주의여서... (nullable 취지를 아예 무시하는 연산자라고 생각해요) 혹시 이건 어떤가요?
```suggestion
        admin.lastAccessTime?.shouldBeGreaterThan prevAccessTime
```
다만 lastAccessTime의 중요도가 낮다는 점, 테스트 코드에서 작성된 점이라는 걸 감안하면 꼭 수정은 안해도 될 거 같아요

2023-02-10 00:08 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
> +        var lastAccessTime: LocalDateTime? = null,
저도 정확히 이 생각하다가 피곤해서 테스트에 일단 !! 박았었습니다.

nullable일 이유가 없는것 같으면 수정할게요

2023-02-11 04:13 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/user/administrator/Administrator.kt
> +        return this.password.value == password.value
아 네 좋네요.

2023-02-11 04:35 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
> +        val password: Password
일단은 controller, service에서 굳이 Password 값 객체 대신 문자열로만 주고 받도록 수정해보았습니다.

2023-02-11 04:37 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/domain/user/administrator/AdministratorTest.kt
> +        admin.lastAccessTime!! shouldBeGreaterThan prevAccessTime
컬럼 타입 자체를 not nullable로 수정하는 방식으로 수정했습니다!

2023-02-11 04:55 UTC, kth990303 requested changes
딱 하나땜에 우선 RC로 해뒀는데, 이 부분 서로 상의해보고 결론나오면 머지하죠!

2023-02-11 04:55 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/Password.kt
> +        return this.value == password.sha256Encrypt()
request뿐만 아니라 비즈니스로직, 도메인 로직에서 값 객체를 사용하지 않고 string으로 바꾼 것 같은데 이렇게 하면 값 객체의 의미가 없어질거같아요.

개인적으로는 클라이언트에서 보내주는 요청 dto에서만 string으로 받고, 비즈니스 로직에서는 값 객체를 이용하는 것이 좋아보이는데 어떻게 생각하시나요?

2023-02-11 05:09 UTC, kth990303 approved these changes
👍

2023-02-11 05:10 UTC, merged