feat: prod 구성 디비 연결 설정
Nexters/nexters-admin-server pull request #13
Opened 2023-02-12 09:36 UTC by ykc415

네이버클라우드에  Cloud DB for PostgreSQL 써서 디비 띄워놨습니다. 

보안보다는 비용 아끼고 대충빨리 만드는게 좋을것같아서 public subnet에 올렸습니다. 

실제 디비 환경에서 개발하고 싶으실 경우는 아래 스샷과 같이

run configurations 에서 active profiles = prod , Environment variables 에 디비 유저, 비밀번호 설정해주셔야합니다. 

![스크린샷 2023-02-12 오후 6 32 07](https://user-images.githubusercontent.com/21697390/218303301-60272503-865e-4b72-9015-cd8025e5e5b6.png)

2023-02-13 04:29 UTC, kth990303 requested changes
수고하셨어요 :)
`ddl-auto` 설정때문에 RC로 남겨봤는데 확인 후 수정 또는 코멘트 남겨주시면 approve하겠습니다.

DB, 스프링 서버가 배포된 덕분에 로컬에서 실제 환경처럼 테스트해볼 수 있겠군요 (dev 서버를 만들 비용은 없으니 ㅠㅠ) 👍

2023-02-13 04:29 UTC, kth990303 commented on src/main/resources/application-prod.yml
> +    url: 'jdbc:postgresql://pg-f8s8l.vpc-pub-cdb-kr.ntruss.com:5432/nexters'
url도 환경변수로 넘겨주는 것에 대해선 어떻게 생각하시나요?

2023-02-13 04:29 UTC, kth990303 commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
`ddl-auto: update`는 배포 환경에 권장되지 않는 설정인데, 혹시 설정한 이유가 따로 있는지 궁금합니다.
참고: https://stackoverflow.com/questions/221379/hibernate-hbm2ddl-auto-update-in-production

엔티티 설정에 맞게 적용되는 옵션이라 자칫하다가 ORM 컬럼 매핑이 의도치 않게 과하게 작동될 수 있을 것 같아서 `ddl-auto: validate`가 더 나아보이는데 어떻게 생각하시나요?
```suggestion
      ddl-auto: validate
```

2023-02-13 04:33 UTC, ykc415 commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
일단 디비에 테이블 만들어두려고 넣은건데 어느정도 테이블 다 만들어지면 변경하면 될것같습니다.

2023-02-13 04:34 UTC, ykc415 commented on src/main/resources/application-prod.yml
> +    url: 'jdbc:postgresql://pg-f8s8l.vpc-pub-cdb-kr.ntruss.com:5432/nexters'
환경변수로 넣어도되는데 url 이 코드에 들어가는게 보안이슈는 아닌것같아서 두었습니다.

2023-02-13 04:49 UTC, bugoverdose reviewed
application-prod.yml을 별도로 두지 않고 하나의 application.yml 파일에서 설정들을 관리하는건 어떨까요? 공통적으로 적용되는 속성과 각 프로파일에 적용되는 속성들을 구분해서 관리할 수 있을 것 같아요.

[참고](https://bugoverdose.github.io/development/spring-profile-and-environment-variables-tutorial/)

2023-02-13 04:49 UTC, bugoverdose commented on src/main/resources/application-prod.yml
> +    url: 'jdbc:postgresql://pg-f8s8l.vpc-pub-cdb-kr.ntruss.com:5432/nexters'
저도 url까지 환경변수로 넘기는게 적절할것 같아요.

2023-02-13 04:52 UTC, kth990303 commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
현재는 사실상 prod 서버가 아닌 dev 서버에 적용할 yml이니 `update`로 둬도 괜찮을 것 같네요.

8주차쯤에 validate로 바꾸는 것도 괜찮겠군요

2023-02-13 04:53 UTC, kth990303 approved these changes
url 환경변수 여부, yml 파일 분리 여부는 저는 크게 상관 없어서 approve로 바꿔둘게요.
성현님이 보시고 취향껏 반영해주시면 될 것 같습니다 :)

2023-02-13 04:56 UTC, bugoverdose commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
저도 릴리즈 전까지는 지금 그대로 가도 괜찮은 것 같아용. create-drop도 되고요.

2023-02-13 04:57 UTC, bugoverdose commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
릴리즈할 때 되면 validate + flyway까지 셋업하면 좋을 것 같아요. 얘기해보고 다들 괜찮다 싶으면 제가 셋업할께요

2023-02-14 00:59 UTC, kth990303 reviewed
`application.yml`에 있는 아래 값들이 `prod.yml`에는 없는 것 같아요

```coffeescript
security.jwt.token:
  secret-key: ${JWT_SECRET_KEY}
  validity: ${JWT_VALIDITY}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
  paths-to-match:
    - /api/**
    - /health-check
```

2023-02-14 05:19 UTC, ykc415 commented
> `application.yml`에 있는 아래 값들이 `prod.yml`에는 없는 것 같아요
> 
> ```coffee
> security.jwt.token:
>   secret-key: ${JWT_SECRET_KEY}
>   validity: ${JWT_VALIDITY}
> 
> springdoc:
>   default-consumes-media-type: application/json
>   default-produces-media-type: application/json
>   api-docs:
>     path: /api-docs
>   swagger-ui:
>     path: /swagger-ui.html
>     disable-swagger-default-url: true
>     display-request-duration: true
>     operations-sorter: alpha
>     tags-sorter: alpha
>   paths-to-match:
>     - /api/**
>     - /health-check
> ```

추가안해도 기본 속성에 덮어씌워지는것 아니였나요? 

일단 추가하긴했습니다.

2023-02-14 15:10 UTC, merged