[개발중] Feat/세션 api
Nexters/nexters-admin-server pull request #14
Opened 2023-02-12 10:03 UTC by ykc415

세션 api 개발중입니다. 

jwt interceptor 쪽이 머지되면 메인 세션 조회 구현할 예정입니다.

2023-02-13 04:44 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
> +        )
`testsupport.Fixtures` 파일 참고해서 createSession라는 함수를 만드는게 좋을 것 같아요.

2023-02-13 04:44 UTC, kth990303 reviewed
몇 가지 코멘트 남겨봤습니다~~

2023-02-13 04:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/controller/session/SessionController.kt
> +import org.springframework.web.bind.annotation.*
import wildcard가 있는데 혹시 의도하신건지 한번 궁금해서 코멘트 남겨봅니다!

2023-02-13 04:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/repository/SessionRepository.kt
> +    fun findByGeneration(generation: Int): List<Session>
이건 어떤가요?
```suggestion
    fun findAllByGeneration(generation: Int): List<Session>
```

2023-02-13 04:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
> +
개행이 2줄이라 한번 코멘트 남겨봅니다

2023-02-13 04:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +class SessionService(
`@Transactional`이 누락돼있어요

2023-02-13 04:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +    }
`findByIdOrNull`은 기본으로 repository에서 제공해주는 확장함수라 개인적으로는 꼭 필요하진 않아 보이기도 하는데 어떻게 생각하시나요?

이미 40번째 라인에서 `findByIdOrNull`을 사용하고 있기도 하구요!

2023-02-13 04:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +        val session = sessionRepository.findByIdOrNull(sessionId) ?: throw BadRequestException("session does not exist")
`exception`패키지에 있는 `CustomExceptions`의 companion object에 sessionNotFound 함수를 별도로 만드는 것이 좋아보여요 (진우님이 작성한 커스텀 에러 컨벤션과 통일 및 ControllerAdvice 예외메시지 컨벤션)

2023-02-13 04:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +        session.apply {
scope function 배워갑니다 😄

2023-02-15 04:52 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +        val session = sessionRepository.findByIdOrNull(sessionId) ?: throw BadRequestException("session does not exist")
+ 예외 메시지 한글로 통일하면 좋을 것 같아요. 아마 FE에서 그대로 사용할 것 같네요.

2023-02-15 04:59 UTC, bugoverdose requested changes
develop과 동기화 + 깃 충돌 해결하고 구현 완료해봅시다.

2023-02-15 04:59 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
> +    }
```suggestion
@ApplicationTest
class SessionServiceTest(
        @Autowired private val sessionService: SessionService
) {
```

2023-02-15 04:59 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/controller/session/SessionController.kt
> +        //Todo jwt에서 유저아이디 가져온다음 유저에 따라 다른 response 를 줘야함
이미 구현된 일반 회원 인증/인가 기능으로도 구현할 수 있을 것 같아요.

2023-02-15 04:59 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/controller/session/SessionController.kt
> +    fun findSessionByGeneration(@RequestParam generation: Int): ResponseEntity<List<Session>> {
```suggestion
    @SecurityRequirement(name = "JWT")
    @GetMapping
    fun findSessionByGeneration(@RequestParam generation: Int): ResponseEntity<List<Session>> {
```

2023-02-19 04:41 UTC, ykc415 commented on src/test/kotlin/nexters/admin/service/session/SessionServiceTest.kt
> +        )
저는 이런 복잡하지않은 mock data 생성을 굳이 function 으로 빼지 않아도 된다고 생각합니다.

2023-02-19 04:41 UTC, ykc415 commented on src/main/kotlin/nexters/admin/controller/session/SessionController.kt
> +import org.springframework.web.bind.annotation.*
intellij  자동 import 로 된것같습니다.

2023-02-19 04:42 UTC, ykc415 commented on src/main/kotlin/nexters/admin/repository/SessionRepository.kt
> +    fun findByGeneration(generation: Int): List<Session>
더 명확한것같아서 suggestion 으로 수정했습니다.

2023-02-19 04:44 UTC, ykc415 commented on src/main/kotlin/nexters/admin/service/session/SessionDtos.kt
> +
수정했습니다.

2023-02-19 04:46 UTC, ykc415 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +class SessionService(
전체 session 작업이 트렌젝션으로 처리되어야할까요?

2023-02-19 04:49 UTC, ykc415 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +    }
어떤의미인지 이해하지못했는데 `findById`를 써야한다 인가요?

2023-02-19 05:44 UTC, ykc415 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +        val session = sessionRepository.findByIdOrNull(sessionId) ?: throw BadRequestException("session does not exist")
반영했습니다

2023-02-19 05:50 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +    }
이 메서드(`findSession`)를 서비스에 정의할 필요가 없어보여서 남긴 코멘트였어요. 해당 메서드가 없어도 sessionRepository.findByIdOrNull을 호출하면 될 것 같아서요

2023-02-19 05:51 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +class SessionService(
세션 생성 및 삭제 작업 시에 acid가 보장되려면 있어야한다고 판단했는데, 현재 상황에서 크게 급한편은 아니긴 합니다.

2023-02-19 05:53 UTC, ykc415 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +    }
물론 가능은 하겠지만 controller에서 repository 를 inject 받아 사용하는건 별로좋지않아보입니다.

2023-02-19 06:05 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/session/SessionService.kt
> +    }
아, id로 직접 찾아오는 api에 사용이 됐군요. 납득됐습니다 저도 동의합니다 :)

2023-02-19 09:16 UTC, ykc415 commented
기수 CRUD api 도 여기다 만들어놨습니다.

2023-02-19 09:55 UTC, kth990303 approved these changes
테스트 CI가 깨지는 부분만 수정되면 선머지 이후리팩터링해도 될 거 같아서 approve 합니다.

테스트 깨짐 현상 수정방법
> 수정방법 1. generation 엔티티에 id 추가
수정방법 2. DatabaseCleanser execute 메서드 로직 일부 변경

2023-02-19 09:55 UTC, kth990303 commented on src/main/kotlin/nexters/admin/controller/generation/GenerationController.kt
> +) {
이후에 Entity 대신 DTO로 리팩터링 해보면 좋을 것 같아요.
나중에 여유되는 팀원이 해보는걸루

2023-02-19 10:13 UTC, merged