Feat/member profile
Nexters/nexters-admin-server pull request #15
Opened 2023-02-13 14:26 UTC by xxeol2

회원 프로필 조회 API를 구현했습니다.
- `내 정보 조회` GET /api/members/me
- `내 출석정보 조회` GET /api/attendance/me

## 의견을 묻고싶은 부분

### 멤버의 해당 기수 정보(GenerationMember)가 없을 경우의 처리

- 해당 기수의 회원이 아닌 회원이 (즉, generation = n 인 GenerationMember정보가 없는 회원) 자신의 출석 정보를 조회했을 때, isGenerationMember는 boolean / data는 null을 보내줍니다.
- data가 null인 경우, ResponseBody에 attendanceData를 추가하지 않을지 혹은 `attendanceData: null`을 포함시킬지 고민했습니다.
    - 이는 명확한 정답이 없다고합니다.
        - [https://stackoverflow.com/questions/15686995/should-null-values-be-included-in-json-responses-from-a-rest-api](https://stackoverflow.com/questions/15686995/should-null-values-be-included-in-json-responses-from-a-rest-api)
    - 일단 `attendanceData: null` 을 포함하는 방법으로 구현했습니다.
        - 클라측에서 undefined보다 null 처리가 간단하지 않을까..라는 개인적인 추측을 통해 결정했습니다.
- 제가 정의한 ResponseBody는 다음과 같은데 너무 depth가 깊어지지 않는지, 속성 이름은 적합한지 의견 묻고싶습니다.
    
    ```coffeescript
    GET /api/attendance/me
    Authorization: Bearer member.jwt.token
    
    ResponseBody {
    		isGenerationMember: Boolean,
    		attendanceData: {
    				score: 80,
    				isCompletable: true,
    				attendances: [{
    						title: string,
    						week: int,
    						sessionDate: LocalDate?,
    						attendanceStatus: string // PENDING, TARDY, ATTENDED, UNAUTHORIZED_ABSENCE, AUTHORIZED_ABSENCE,
    						attendanceTime: LocalDateTime?
    						score: int // -15, -10, -5, 0
    		    }]
    		}?
    }
    ```
    

### 테스트내 메서드 분리

- 테스트 함수가 너무 길어져서 Attendance 객체를 생성하고 저장소에 저장하는 과정의 하나의 private 함수 `generateAttendance`로 분리했습니다.
- 테스트 함수의 길이 단축을 위해 이렇게 메서드를 분리하는 형식이 옳은지 궁금합니다.

### 기타 구조 및 코드에 대한 피드백들

---
## TODO

- 현재 진행중인 기수 정보를 저장하고 알아낼 방법을 찾아내, “내 출석 정보 조회”에 적용해야합니다.
    - 현재 나온 후보로는
        1. generation(int) / ongoing(boolean) 값 가지는 Generation 테이블 생성
        2. generation(int) 값 가지는 Generation 테이블 생성 후 가장 큰 generation 값 고르기
        
        가 있습니다.

2023-02-13 14:28 UTC, xxeol2 commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.jpa' version '1.6.21'
제 IntelliJ에서 build.gradle파일 컨벤션이 맞지 않는 것 같습니다 ㅠ
설정좀 알려주실 수 있나요?

2023-02-13 14:59 UTC, bugoverdose commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.jpa' version '1.6.21'
전 일단 이런데 다른 분들도 이거 보고 맞는지 다들 비교해주실 수 있나요?

<img width="290" alt="image" src="https://user-images.githubusercontent.com/73531614/218485801-c93b35f6-c3c7-489c-ac92-347ebe98e832.png">

2023-02-13 14:59 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
> +        val member: Member = memberRepository.save(createNewMember(name = "김태현"))
별건 아니구. 이거 구현할 때 그냥 코드 구현하는 사람 이름 넣는거 어떤가요?

2023-02-13 14:59 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/attendance/AttendanceStatus.kt
> +    AUTHORIZED_ABSENCE("통보결석", -10),
중요한건 아닌데, `score` 대신 `penaltyScore`는 어떤가요?

```suggestion
enum class AttendanceStatus(val value: String, val penaltyScore: Int) {
    PENDING("대기", 0),
    ATTENDED("출석", 0),
    TARDY("지각", 5),
    UNAUTHORIZED_ABSENCE("무단결석", 15),
    AUTHORIZED_ABSENCE("통보결석", 10),
```

2023-02-13 14:59 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/repository/AttendanceRepository.kt
> +    fun findAllByGenerationMemberIdAndAttendanceStatusIn(generationMemberId: Long, statuses: List<AttendanceStatus>): List<Attendance>
JPA를 사용할 때 이렇게 메서드명이 엄청 길어지는 경우, **별도의 메서드로 감싸서** 호출하는 방법도 생각해볼 수 있어요. 다양한 방법이 있는데, 예를 들어 아래처럼 하면 `attendanceRepository.findGenerationMembersOf(~,~)`처럼 호출할 수 있을 듯해요. 예시라 메서드명은 임의로 정했습니다. (클라이언트 쪽에서 findGenerationMembersOf 메서드에 대해 import 필요) 

```kotlin
fun AttendanceRepository.findGenerationMembersOf(generationMemberId: Long, statuses: List<AttendanceStatus>): List<Attendance> {
    return findAllByGenerationMemberIdAndAttendanceStatusIn(generationMemberId, statuses)
}

interface AttendanceRepository : JpaRepository<Attendance, Long> {
    fun findAllByGenerationMemberIdAndAttendanceStatusIn(generationMemberId: Long, statuses: List<AttendanceStatus>): List<Attendance>
}
```

P.S. 자바의 경우 인터페이스 내부에 default 메서드를 구현하는 방법이 있습니다.

2023-02-13 14:59 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +        val isGenerationMember: Boolean,
참고 자료 기록: https://stackoverflow.com/questions/32270422/jackson-renames-primitive-boolean-field-by-removing-is

2023-02-13 14:59 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +        val ongoingGeneration = 22;
생각해봤는데, `ongoingGeneration`이라는 값을 프로그램 실행 시점에 환경변수로 주입하는 것도 좋으려나 싶네요

2023-02-13 14:59 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/user/MemberDtos.kt
> +            )
기획 관련인 것 같아서 FE 쪽에도 공유하면 좋을 것 같아요. 사소하다 싶으면 사후통보하죠.

2023-02-13 14:59 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
> +    }
#12 머지되면 그쪽에 구현해놓은 `@ApplicationTest`라는 어노테이션 활용 바람!

2023-02-13 14:59 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
> +        generateAttendance(session4, generationMember)
given 절만 10줄이나 되는데 뭔가 복수의 엔티티를 저장해주는 private 메서드를 구현해서 사용하는건 어떨까도 싶네요.

2023-02-13 15:04 UTC, xxeol2 commented on src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
> +        val member: Member = memberRepository.save(createNewMember(name = "김태현"))
좋아요! 위의 테스트코드와 통일하다보니 태현님 이름 사용했네요ㅎ 제 이름으로 수정할게요!

2023-02-13 15:06 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/domain/attendance/AttendanceStatus.kt
> +    AUTHORIZED_ABSENCE("통보결석", -10),
`score`라는 명칭이 출석 점수와 혼동되는 것 같네요! ResponseBody에서도 해당 속성명 `penaltyScore`로수정하겠습니다

2023-02-13 15:09 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +        val ongoingGeneration = 22;
오.. 그것도 좋은 방법인 것 같습니다!!

2023-02-13 15:23 UTC, xxeol2 commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.jpa' version '1.6.21'
저두 얘랑 동일하네요!

2023-02-14 06:07 UTC, kth990303 requested changes
수고하셨어요~
`여러 기수를 참여한 회원의 출석정보를 반환하는 경우`에서 의도치 않은 순서대로 데이터를 반환할 것 같아서 RC를 남겼지만! 기획적 이슈 또는 제가 로직을 잘못 이해한 걸수도 있으니 확인해보시고 코멘트 부탁드립니다.

2023-02-14 06:07 UTC, kth990303 commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.jpa' version '1.6.21'
저도 groovy, java 모두 진우님과 동일합니다

2023-02-14 06:07 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +        val attendances: List<AttendanceResponse>
저는 내 출석정보를 보여줄 때 현재 기수에 대한 정보만 보여주면 되지 않을까 생각했었어요.

따라서 responseBody를 아래와 같이 생각했었는데, 혹시 활동한 모든 기수에 대한 출석 정보를 보여줘야한다고 기획적 결론이 나왔을까요? 
```coffeescript
GET /api/attendance/me
Authorization: Bearer member.jwt.token

ResponseBody {
    isGenerationMember: Boolean,
    score: 80,
    isCompletable: true,
    attendances: [{
	title: string,
	week: int,
	sessionDate: LocalDate?,
	attendanceStatus: string // PENDING, TARDY, ATTENDED, UNAUTHORIZED_ABSENCE, AUTHORIZED_ABSENCE,
	attendanceTime: LocalDateTime?
	score: int // -15, -10, -5, 0
    }]
}
```

2023-02-14 06:07 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +                    }
취향 차이일 거 같은데 `it`키워드로 줄여쓸 수 있기는 해요. 다만, `session`, `attendance`를 명확하게 드러낼 수 있다는 장점이 줄어들긴 할 것 같군요

```suggestion
                    sessionToAttendance.map { AttendanceResponse.of(it.key, it.value) }
```

2023-02-14 06:07 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +    fun getProfile(loggedInMember: Member): FindProfileResponse {
`@Transactional(readOnly = true)` 있으면 더 좋을 거 같아요

2023-02-14 06:07 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +    fun getAttendanceProfile(loggedInMember: Member): FindAttendanceProfileResponse {
여기에도 `@Transactional(readOnly=true)`붙여도 될 거 같아요

2023-02-14 06:07 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +    }
둘이 메서드 순서 바뀌면 좋을 거 같아요
`getWeekSortedSessionToAttendance`는 35번째 라인에서 쓰이고 `getValidAttendanceStatuses`은 30번째 라인에서 쓰여서 좀 더 잘 읽히려면 순서 바꾸는게 더 좋을듯한 느낌?

2023-02-14 06:07 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +    }
같은 기수에 대한 여러 week일 때는 의도한 대로 잘 반환하는 좋은 로직일 것 같은데, 만약 여러 기수에 대한 출석정보가 담겨있으면 아래처럼 여러 주차가 섞인 상태로 반환될 거 같아서 조금 걱정되네요

```coffeescript
ex) 
19기 1~8주차, 20기 1~9주차, 22기 1~8주차

result)
20기 9주차
19기 8주차
20기 8주차
22기 8주차
... 
```

2023-02-14 06:07 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
> +        val member: Member = memberRepository.save(createNewMember())
기수가 섞인 상태의 테스트 케이스도 있으면 좋을 거 같아요

2023-02-14 06:07 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
> +        val member: Member = memberRepository.save(createNewMember())
이런 경우가 있을지 모르겠지만 만반의 대비 좋네요 👍

2023-02-14 13:27 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +        val attendances: List<AttendanceResponse>
저도 태현님과 똑같이 현재 기수에 대한 출석정보만 보여주면 되는걸로 이해했어요!
그래서 attendanceData는 배열 형식이 아니라 하나의 오브젝트입니다!
그러면 속성들(isScore, isCompletable, attendances)를 왜 또 하나의 오브젝트로 감싼건가.. 물으신다면
isGenerationMember이 true일 때만 보내줄 속성값들이기 때문입니다!
(false일땐 모두 null이기때문에, 그냥 출석 정보 관련 속성들을 하나의 객체로 묶어서 객체 자체를 null로 보내버림)

isGenerationMember가 false인 경우 "현재 기수 회원이 아닙니다"라는 문구를 띄워줄 것 같기때문에 다른 속성들을 읽을 필요가 없을 것 같습니다..
이것 관련해서 의견을 묻고싶어요!
## 현재 기수에 참여중이지 않은 회원의 경우
### 1. attendanceData로 묶어주기 (현재 개발한 형식)
```
ResponseBody {
    isGenerationMember: false,
    attendanceData: null
}
```
### 2. 풀어서 쓰기 (태현님이 제안한 방식)
```
ResponseBody {
    isGenerationMember: false,
    score: null,
    isCompletable: null,
    attendances: null
}
```
두가지 중 어떤 방식이 더 나은 방식일까요?

2023-02-14 13:29 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +                    }
저도 둘 중에 고민하다가 `session`, `attendance`를 명확하게 드러내는쪽이 나을 것 같아서 저렇게 개발했습니다!
다만, 다시 생각해보니 앞서 사용한 변수명 자체가 `sessionToAttendance`이기 때문에 `it.key`, `it.value`해도 `session`과 `attendance`임이 명확하게 드러나는 것 같네요!
제안해주신 방향으로 수정하겠습니다!

2023-02-14 13:35 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +    }
메서드 순서도 신경써야하는 부분인데.. 신경을 못썼네요!
꼼꼼한 리뷰 감사합니다 😄

2023-02-14 13:45 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +    }
`sessionToAttendance`를 만드는 과정은 다음과 같습니다.
1. 출석 정보를 불러 올 때 `generationMemberId`로 find해옵니다.(findAllByGenerationMemberId...)
2. 뽑아진 출석 정보들속 `sessionId`만 뽑아내서 세션 정보들과 매핑해줍니다.

따라서  `sessionToAttendance`에는 한 기수에 대한 출석 정보만 담기게 됩니다.

만약, generation가 올바르지 않은 세션(즉, 다른 기수의 세션)과 연결되어있다면 태현님이 말씀하신 것과 같은 문제가 발생할 수 있을 것 같습니다.
이는 데이터 무결성이 깨진 상황인 것 같습니다.
(다른 기수의 세션에 대한 출석 정보가 한 `generationMemberId`와 연결되어있기때문에)

제가 말한 경우를 대비해주는게 좋을까요?!

대비한다면 아마 출석정보와 맵핑된 세션 정보 중, 현재 기수 세션만 필터로 걸러내는 방식이 될 것 같습니다.

2023-02-14 13:58 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +    }
아 전체기수 뽑아오는 줄 알았네요. 로직 괜찮다면 별도로 체크는 안해줘도 될거같슴니다 :)

2023-02-14 14:01 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +        val attendances: List<AttendanceResponse>
흐음 그러네요 true인 경우에만 보내줄 거라면 전자가 나을 거 같네요.
이대로 하는게 더 좋을 것 같습니다! 불필요하게 많은 데이터를 보내주는 것보다 나을거같네요

2023-02-14 14:02 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
> +        val member: Member = memberRepository.save(createNewMember())
전체 기수 불러오는 줄 알고 추가로 남겼던 말인데, 그냥 이 테케에다가 generation = 다른거만 추가하거나 아니면 안만들어도 상관없응 거 같아요.

2023-02-14 14:03 UTC, kth990303 approved these changes
로직 재확인 및 데이터 응답 이유 확인돼서 approve로 바꿉니다 :) 수고하셨어요

2023-02-14 14:22 UTC, xxeol2 commented on src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
> +        val member: Member = memberRepository.save(createNewMember())
해당 정보들이 모두 같은 generation임을 테스트하는 코드를 생성할게요!

2023-02-14 14:26 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/repository/AttendanceRepository.kt
> +    fun findAllByGenerationMemberIdAndAttendanceStatusIn(generationMemberId: Long, statuses: List<AttendanceStatus>): List<Attendance>
오,, 하나 배워갑니다!! 반영할게요 🤓

2023-02-14 14:45 UTC, xxeol2 commented on src/test/kotlin/nexters/admin/service/attendance/AttendanceServiceTest.kt
> +        generateAttendance(session4, generationMember)
저런것들을 통째로 saveSessionsAndAttendances 와 같은 private 메소드로 분리하는 방식을 말씀하시는걸까요?
```java

    @Test
    fun `내 출석정보 조회시 PENDING이 아닌 정보들만 불러온다`() {
        val member: Member = memberRepository.save(createNewMember())
        val generationMember: GenerationMember = generationMemberRepository
                .save(createNewGenerationMember(memberId = member.id))
        saveAttendanceDataWithStatuses(generationMember)

        val attendanceProfile = attendanceService.getAttendanceProfile(member)
        attendanceProfile.attendanceData!!.attendances.run {
            size shouldBe 4
            map { it.attendanceStatus } shouldNotContain AttendanceStatus.PENDING
        }
    }

    private fun saveAttendanceDataWithStatuses(generationMember: GenerationMember) {
        val session1: Session = sessionRepository.save(createNewSession())
        val session2: Session = sessionRepository.save(createNewSession(week = 2))
        val session3: Session = sessionRepository.save(createNewSession(week = 3))
        val session4: Session = sessionRepository.save(createNewSession(week = 4))
        val pendingSession: Session = sessionRepository.save(createNewSession(week = 5))
        generateAttendance(session1, generationMember, AttendanceStatus.ATTENDED)
        generateAttendance(session2, generationMember, AttendanceStatus.TARDY)
        generateAttendance(session3, generationMember, AttendanceStatus.UNAUTHORIZED_ABSENCE)
        generateAttendance(session4, generationMember, AttendanceStatus.AUTHORIZED_ABSENCE)
        generateAttendance(pendingSession, generationMember, AttendanceStatus.PENDING)
    }
```
이렇게 묶어서 private 메서드로 분리를 해봤는데, 메서드 네임 길이가 지옥이긴 하네요 😂

2023-02-14 16:10 UTC, merged