feat: CSV 파일 기반 회원 복수 생성 API 구현
Nexters/nexters-admin-server pull request #34
Opened 2023-02-19 15:48 UTC by bugoverdose

이번 프로젝트의 복잡한 구현 두 번째입니다. 테스트 코드가 부족한 상황입니다.

2023-02-19 15:56 UTC, bugoverdose commented on src/test/resources/testdata.csv
> +김민수,남자,ming@gmail.com,01012345679,운영진,CTO,수료
csv 파일 형식 참고.

참고로 name,gender... 순서가 아니라 gender,name... 순서여도 괜찮습니다. 컬럼명만 정확하게 입력하고, 누락된 데이터만 없으면 됩니다.

2023-02-19 15:56 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +        generationMemberRepository.saveAll(generationMembers.findAllByMemberIdsNotIn(savedMembers.map { it.id }))
엑셀 파일을 Map으로 넘겨받은 이후의 실질적인 비즈니스 로직

- member가 없으면 생성, 있으면 수정
- generationMember가 없으면 생성, 있으면 수정 + 위에서 생성한 memberId 값과 맵핑

2023-02-19 15:56 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMember.kt
> +        var memberId: Long? = null, // TODO: nullable looks dangerous. needs checkup.
nullable일 이유가 있는지 다소 의문이 들어서 메모만 해놨습니다.

2023-02-21 05:15 UTC, kth990303 requested changes
우선은 테스트코드 누락이랑 로직 중복때문에 RC를 남겼지만, 늦어도 수요일 낮까진 Approve 및 머지 예정입니다~~

2023-02-21 05:15 UTC, kth990303 commented on src/main/kotlin/nexters/admin/support/utils/CsvParseUtils.kt
> +            columnValues[colName] = values
만약 세부직군이 없는 디자이너의 경우, 해당 세부직군은 빈칸 vs null로 변환하여 넣어주기?
현재는 빈칸으로 넘겨주고 있는 것 같고, 저도 빈칸에 동의하는데 확실하게 기획적으로 정해져야될 것 같긴 해서 코멘트 남겨봐요 :)

2023-02-21 05:15 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +        }
오 이거 좋네요
확실히 generateDefaultPassword가 Member 엔티티클래스에 있으면 더 좋을 거 같네요

2023-02-21 05:15 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMember.kt
> +        var memberId: Long? = null, // TODO: nullable looks dangerous. needs checkup.
`nullable`하지 않아도 될 거 같아요.
회원이 삭제됐을 때 기수회원 연관관계 매핑 제대로 돼있지 않은 경우 (기수회원은 삭제되지 않고 남아있는 경우) 때문에 nullable로 했던 것 같은데... 지금 생각해보니 굳이 싶네요. 오히려 위험하다는 거에 동의

2023-02-21 05:15 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMembers.kt
> +        }
이 로직이 Members 클래스와 중복되는데, 사실 이 부분은 CsvResult 결과를 validate하는 느낌이라 CsvParseUtils 클래스의 확장함수로 해도 될 거 같아요.

아래 느낌은 어떤가요?

### CsvParseUtils.kt
```kotlin
fun validateCsvResult(members: Map<String, List<String>>, requiredKeys: List<String>) {
    if (members.isEmpty()) {
        throw BadRequestException.wrongCsvFile()
    }
    if (!members.keys.containsAll(requiredKeys)) {
        throw BadRequestException.wrongCsvFile()
    }
    if (members[EMAIL]!!.size != setOf(members[EMAIL]).size) {
        throw BadRequestException.duplicateEmail()
    }
}
```


### GenerationMembers.kt
```kotlin
fun of(
            // 정적 팩터리 메서드 프로퍼티
): GenerationMembers {
    validateCsvResult(generationMembers, REQUIRED_KEYS) // Csv 확장함수 사용
    val emailToMemberIdMap = mapMemberIdByEmail(savedMembers)
    // 로직
}
```

2023-02-21 05:15 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMembers.kt
> +        val curGenMemberMap = mapByMemberId(curGenMembers)
아래와 같은 변수명은 어떤가요?
```suggestion
        val currentGenerationMemberMap = mapByMemberId(currentGenerationMembers)
```

또는

```suggestion
        val currentGenerationMembersAndIds = mapByMemberId(currentGenerationMembers)
```

2023-02-21 14:11 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMember.kt
> +        var memberId: Long? = null, // TODO: nullable looks dangerous. needs checkup.
일단 수정 완료 4c6a62c

2023-02-21 14:15 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMembers.kt
> +        val curGenMemberMap = mapByMemberId(curGenMembers)
으음 뭔가 전반적으로 의미를 좀 더 부여해보죠. 너무 알고리즘 문제 풀듯이 변수명을 대충 적은 것 같긴하네요.

2023-02-21 14:26 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMembers.kt
> +        }
개인적으로 utils에 가기에는 너무 비즈니스 로직이랑 엮여있는것 같아서 domain쪽에 넣은거긴 한디. 다시 보니 리팩터링하면 좋을 것 같긴하네요.

2023-02-21 14:34 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMembers.kt
> +        }
혹시 이런 느낌은 어떤가요? 97b708a

2023-02-21 14:34 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/generation_member/GenerationMembers.kt
> +        val curGenMemberMap = mapByMemberId(curGenMembers)
이런 느낌은 어떱니까 b373e3f

2023-02-21 15:00 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/support/utils/CsvParseUtils.kt
> +            columnValues[colName] = values
빈 문자열이 전달되는 현재 상황이 더 잘 이해되도록 테스트 데이터 추가해놨습니다. 235c4ea

2023-02-21 15:24 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/support/utils/CsvParseUtils.kt
> +            columnValues[colName] = values
null이 아니라 빈 문자열이 들어가면 from에서 깨지는군요. 디자이너의 경우 무조건 실패하는 상황이었네요
<img width="832" alt="image" src="https://user-images.githubusercontent.com/73531614/220384280-76ec7f90-dc6f-47d4-a1f8-d25811d542fe.png">

6a9e8bc
- Position과 SubPostion 쪽에서 빈문자열과 null 모두 대응할 수 있도록 수정해봤는데 확인 바랍니다. 
- 둘이 같은 기능을 미묘하게 다르게 다루고 있어서 통일해보았습니다.

2023-02-21 15:33 UTC, kth990303 approved these changes
중복 로직 제거 잘된거같아요
수고하셨습니다~
테스트는 급한 건 아닌 거 같아서 approve로 했는데, 아래 코멘트 보고 확인부탁드려요!

2023-02-21 15:33 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/generation_member/SubPosition.kt
> +        }
아예 null을 반환해야되는 상황이라면 아래와 같이 예외를 반환하는 상황을 서비스에 위임하고, 도메인에는 아래와 같이 하는 게 나을 거 같아요
```suggestion
            return values().firstOrNull { it.value == value }
        }
```

2023-02-21 16:31 UTC, bugoverdose commented
테스트 몇 가지 작성하면서 일단 서비스 계층에서 확인되는 버그 다 잡았습니다. f90460a

2023-02-22 03:17 UTC, kth990303 approved these changes
테스트 추가 👍

2023-02-22 03:17 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
> +                "status" to mutableListOf("미이수", "수료", "제명")
excel input 이 중복되긴 하는데, 크게 상관없을 듯?
오히려 가독성면에선 더 좋을수도

2023-02-22 08:15 UTC, merged