feat: 로그인 및 비밀번호 수정 API 구현
Nexters/nexters-admin-server pull request #4
Opened 2023-02-02 07:33 UTC by bugoverdose

### 구현 기능

구현한 API만 보면 두 가지입니다.
- POST /api/users/login : 이메일 + 비밀번호 받아서 토큰 반환
- PUT /api/users/password : 헤더로 토큰 받고, JSON으로 비밀번호 받아서 비밀번호 수정

너무 PR 규모가 커지고 있어서 일단은 스탑했고, 자세한 사항은 아래에 커멘트로 남길 예정입니다.

### TODO

- API 문서화
- 로깅
- 테스트 컨벤션 확정해서 테스트 셋업 및 테스트 코드 작성
- `@ControllerAdvice`에 bean validation에 따른 예외 처리 추가

2023-02-02 08:26 UTC, bugoverdose reviewed
일단 현재 초기 구현에 대한 피드백 받습니다.

개인적으로 패키지 구성이 특히 불편한데 개선사항 있으면 자유롭게 알려주십쇼

2023-02-02 08:26 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/auth/JwtTokenProvider.kt
> +        @Value("\${security.jwt.token.validity}") private val expirationTime: Long,
테스트 환경과 배포 환경 구분을 위해 토큰 발급에 필요한 secret key와 토큰 유효기간 정보는 `application.yml`에서 설정하고 주입받을 수 있도록 설정했습니다.

2023-02-02 08:26 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/common/exception/ExceptionControllerAdvice.kt
> +    }
커스텀 예외 클래스들과 `@ControllerAdvice`를 활용해서 예외 발생시 그에 해당되는 상태코드 + 예외 메시지를 반환하도록 설정했습니다.

2023-02-02 08:26 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/common/exception/CustomExceptions.kt
> +class NotFoundException(message: String?) : RuntimeException(message) {
커스텀 예외 클래스는 상태코드별로 구현했습니다. 

- 400, 401, 403, 404
- 그 외에 문제 발생시 500 사용

2023-02-02 08:26 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/common/auth/LoginUserResolver.kt
> +    }
코드 중복 최소화를 위해 `ArgumentResolver`에서 토큰으로 사용자(Member)를 찾아 컨트롤러에 직접 반환하도록 구현하였습니다.

2023-02-02 08:26 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
> +)
service와 controller 양쪽에서 사용되는 DTO인데 의존성 방향을 service <= controller로 향하게 하고자 여기에 뒀습니다.

아예 dto, service, controller 패키지로 구분하는게 덜 헷갈릴려나 고민되네요.

2023-02-02 09:05 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +    }
일단 전자대로 했는데 후자가 더 명시적이라는 느낌이 드네요
`비밀번호 검증` vs `잘못된 비밀번호 입력시 예외`
`비밀번호 수정` vs `비밀번호 수정시 초기화 여부도 수정`

2023-02-03 05:22 UTC, kth990303 requested changes
인증/인가 로직 구현량이 많았을텐데 빠르게 정말 잘해주셨다고 생각합니다 👍 
추가로 spring-security 의존성 때문에 기본적으로 아래 화면이 보이는데, spring-security를 사용하지 않는 방향으로 간다면 의존성을 제거해도 될 것 같아요
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/57135043/216519020-9814e272-8074-4398-a321-7d4d2341df58.png">

추가로 몇 가지 코멘트 남겨봤는데 확인 부탁드려요.

2023-02-03 05:22 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/auth/AuthService.kt
> +        val jwtTokenProvider: JwtTokenProvider
접근 제어자 명시해주면 좋을 듯합니다.
```suggestion
        private val memberRepository: MemberRepository,
        private val jwtTokenProvider: JwtTokenProvider
```

2023-02-03 05:22 UTC, kth990303 commented on src/main/resources/application.yml
> +    username: sa
yml 확장자로 변경 👍

2023-02-03 05:22 UTC, kth990303 commented on src/test/kotlin/nexters/admin/common/auth/JwtTokenProviderTest.kt
> +private const val INVALID_SECRET_KEY = "wrongtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
KEY 값이 길어서 120자가 넘어가는데 중간에 엔터 넣는 것 어떻게 생각하시나요?
```suggestion
private const val VALID_SECRET_KEY =
        "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
private const val INVALID_SECRET_KEY =
        "wrongtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
```
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/57135043/216501519-2854f22d-4521-4d03-9b77-a906e18675ef.png">

2023-02-03 05:22 UTC, kth990303 commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +        val member = Member("정진우", Password("1234"), "jweong@gmail.com", Gender.MALE, "01012345678", MemberStatus.NOT_COMPLETION, true)
현재는 멤버 프로퍼티에 변화가 생기면 테스트 코드가 전부 변해야될 것 같아요.
지금 수정하기엔 규모가 좀 커질 수 있으니 패스하고, 이후에 부생성자 또는 companion object를 이용한 테스트 픽스쳐를 만들어두면 더 좋을 것 같아요.

2023-02-03 05:22 UTC, kth990303 commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +    }
저는 후자에 한 표 하고 싶습니다!

2023-02-03 05:22 UTC, kth990303 commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +        member.isInitPassword shouldBe false
저는 비밀번호 수정 시 초기화 여부에 초점을 맞춘 테스트라 생각돼서 `member.password.value`를 검증할 필요는 없어보이는데 어떻게 생각하시나요?

2023-02-03 05:22 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +    }
해당 메서드에는 `@Transactional(readOnly = true)`를 붙여주는 게 좋아보여요

2023-02-03 05:22 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/auth/AuthService.kt
> +        member.validatePassword(request.password)
Member 클래스에 `init`을 추가하여 validatePassword를 넣어주어 도메인에 책임을 위임해보면 좋을 거 같은데 어떻게 생각하시나요?

### Member.kt
```kotlin
class Member(...) {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long = 0L

    init {
        validatePassword(password)
    }

    fun validatePassword(password: Password) {
        if (this.password.value != password.value) {
            throw UnauthenticatedException.loginFail()
        }
    }

```

2023-02-03 05:22 UTC, kth990303 commented on src/test/kotlin/nexters/admin/common/auth/JwtTokenProviderTest.kt
> +    fun `다른 키로 발급된 토큰 해석`() {
JwtTokenProvider 예외 테스트까지 👍 
지금은 아니구 이후에 토큰 만료 여부도 테스트 작성해보면 좋을 것 같네요.

2023-02-03 05:22 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +        this.isInitPassword = false
초기화를 한번 진행했는지 물어보는 로직이니까 `true`로 바껴야되지 않나요?
Member에서 `isInitPassword`의 디폴트 값이 `false`로 지정돼있는 이유기도 하다고 생각해요.
제가 도메인 로직 이해를 잘못하고 있는건지 궁금합니다.
```suggestion
        this.isInitPassword = true
```

2023-02-03 05:22 UTC, kth990303 commented on src/main/kotlin/nexters/admin/controller/user/MemberController.kt
> +            @RequestBody @Valid request: UpdatePasswordRequest): ResponseEntity<Void> {
아래와 같이 `)`에 개행을 넣어주어 아래 그림처럼 컨벤션이 되면 조금 더 이쁠 것 같은데 어떻게 생각하시나요? 개인 취향에 따라 갈릴 것 같네요 ㅎㅎ
```suggestion
    @PutMapping("/password")
    fun updatePassword(
            @LoggedInMember member: Member,
            @RequestBody @Valid request: UpdatePasswordRequest
    ): ResponseEntity<Void> {
```
<img width="491" alt="image" src="https://user-images.githubusercontent.com/57135043/216518117-f2fff0b5-652c-4b6c-b5a7-12d8c4bb2d4a.png">

2023-02-03 05:22 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
> +)
저는 둘 다 좋습니다~ 
나중에 dto가 많아지면 service나 controller 패키지 내에 별도의 dto 패키지를 만들어도 괜찮을 것 같고요.

2023-02-03 05:22 UTC, kth990303 commented on src/main/kotlin/nexters/admin/common/exception/CustomExceptions.kt
> +class NotFoundException(message: String?) : RuntimeException(message) {
와우 너무 좋습니다~ 😄

2023-02-03 05:23 UTC, kth990303 commented
추가로, `common`이라는 패키지명 대신 `support`라는 패키지명도 좋아보이는데 어떻게 생각하시나요?
auth, annotation 등을 통해 개발자가 비즈니스 로직에 집중할 수 있도록 support 해주는 패키지라는 생각도 들어서요.

2023-02-03 05:23 UTC, kth990303 reviewed
추가로, common이라는 패키지명 대신 support라는 패키지명도 좋아보이는데 어떻게 생각하시나요?
auth, annotation 등을 통해 개발자가 비즈니스 로직에 집중할 수 있도록 support 해주는 패키지라는 생각도 들어서요.

2023-02-03 05:25 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/auth/AuthService.kt
> +        member.validatePassword(request.password)
Password 8~20자라는 검증이 추가됐기 때문에, 이부분에 대한 테스트 코드를 작성해주면 더 좋을 것 같습니다.

2023-02-03 07:30 UTC, xxeol2 reviewed
인증/인가 부분 꼼꼼하게 작업해주셔서 많이 배워갑니다 👀
추가로 refresh token 관련 내용들 회의해보면 좋을 것 같아요!

2023-02-03 07:30 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
> +)
저두 태현님 말씀에 동의합니다!
+) 나중에 QueryDSL을 사용하게되면 repository 패키지안에도 dto 패키지 생성하면 좋을 것 같아요!

2023-02-03 07:30 UTC, xxeol2 commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +    }
저도 후자가 더 명시적인 것 같아요!
전자의 경우 코드를 보면서, 어떠한 테스트인지 파악하는 과정이 필요한 것 같아요

2023-02-03 07:30 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
> +                message = "비밀번호는 알파벳, 숫자, 특수문자(!,@,#,\\,$,%,^,*) 8~20 글자로 구성되어야 합니다.")
특수문자 1개 이상 포함등과 같은 규칙도 적용하면 좋을 것 같아요! 토요일 회의때 얘기해보아요!!
[관련 정규식](https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a)

2023-02-03 15:00 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/auth/AuthService.kt
> +        val jwtTokenProvider: JwtTokenProvider
반여완료

2023-02-03 15:10 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/common/auth/JwtTokenProviderTest.kt
> +private const val INVALID_SECRET_KEY = "wrongtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest"
아 그냥 최대한 길이를 줄여보겠습니다.

2023-02-03 15:17 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +        member.isInitPassword shouldBe false
테스트 메서드명이 `비밀번호 수정`라서 넣었던건데, `비밀번호 수정시 초기화 여부도 수정`로 수정하면 필요없을 것 같네요.

2023-02-03 15:21 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +    }
반영 완료

2023-02-03 15:23 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/common/auth/JwtTokenProviderTest.kt
> +    fun `다른 키로 발급된 토큰 해석`() {
그냥 지금 반영 완료

2023-02-03 15:25 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +        val member = Member("정진우", Password("1234"), "jweong@gmail.com", Gender.MALE, "01012345678", MemberStatus.NOT_COMPLETION, true)
그쵸. 테스트 픽스쳐 어떻게 할 것인지에 대해 얘기해보면 좋을 것 같아요.

2023-02-03 15:26 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +    }
반영 완료

2023-02-03 15:34 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/auth/AuthService.kt
> +        member.validatePassword(request.password)
`init` 부분이 잘 이해가 안되는데 혹시 `validatePassword`라는 네이밍이 좀 혼란을 유발하는걸까요?

2023-02-03 15:35 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/auth/AuthDtos.kt
> +)
일단은 이대로 보류하겠슴다

2023-02-03 15:40 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +        this.isInitPassword = false
아 저는 `isInitPassword`을 `isInitialPassword`, 즉 1234처럼 전화번호를 활용한 `초기 비밀번호 상태이냐 아니냐`로 이해했어요.
그래서 처음에 저장될 때는 `true`고 비밀번호 수정시, `false`가 된다고 이해했던거고요.

개인적으로 조금 네이밍이 헷갈리는데 내일 좀 얘기해볼까요?

2023-02-03 15:42 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
> +                message = "비밀번호는 알파벳, 숫자, 특수문자(!,@,#,\\,$,%,^,*) 8~20 글자로 구성되어야 합니다.")
좋습니다👍 기획 차원에서 얘기해보면 좋을 것 같아요.

P.S. 참고로 저는 [이 사이트](https://regexr.com/) 활용합니다.

2023-02-03 15:44 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/controller/user/MemberController.kt
> +            @RequestBody @Valid request: UpdatePasswordRequest): ResponseEntity<Void> {
아 네 저도 좋아요. 이미 다른 곳들에서 그렇게 구현되어있고요.

이런 것들 잡기 위해 ktlint 도입해야겠네요.

2023-02-03 15:55 UTC, bugoverdose commented
> 추가로, common이라는 패키지명 대신 support라는 패키지명도 좋아보이는데 어떻게 생각하시나요? auth, annotation 등을 통해 개발자가 비즈니스 로직에 집중할 수 있도록 support 해주는 패키지라는 생각도 들어서요.

`support`도 나쁘지 않네요. `extensions` 패키지까지 `support`에 넣는건 어떨까요?

<img width="282" alt="image" src="https://user-images.githubusercontent.com/73531614/216647858-965f8b67-b4f2-4b5d-ad4f-b1e72bd485f7.png">

2023-02-03 16:04 UTC, bugoverdose commented
> 인증/인가 로직 구현량이 많았을텐데 빠르게 정말 잘해주셨다고 생각합니다 👍 추가로 spring-security 의존성 때문에 기본적으로 아래 화면이 보이는데, spring-security를 사용하지 않는 방향으로 간다면 의존성을 제거해도 될 것 같아요 

사실 `BCryptPasswordEncoder`로 솔트까지 추가한 단방향 해싱을 한다면 필요할 것 같은데, 일단은 지워놓을까요?

2023-02-04 04:32 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/auth/AuthService.kt
> +        member.validatePassword(request.password)
`validatePassword`가 비밀번호 형식을 검증해주는 메서드인줄 알았는데, 비밀번호 입력을 맞게 했는지 확인하는 메서드였군요.
`checkSamePassword` 역할로 봐야겠네요. 확인했습니다~

2023-02-04 04:47 UTC, xxeol2 approved these changes

2023-02-04 04:58 UTC, kth990303 requested changes
수고하셨습니다~ 리뷰 반영 모두 확인했습니다.
`isInitPassword` 관련 내용때문에 RC로 했는데 이 부분 고쳐지면 approve하겠습니다.

이후에 서비스 통합테스트 (로그인이 잘 되는지, 비밀번호 수정 잘 되는지) 추가되면 좋을 거 같아요

2023-02-04 04:58 UTC, kth990303 commented on src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
> +
이거 클래스명 `MemberDtos`는 어떤가요? 
`UserDtos`도 좋은 거 같은데 Admin이랑 Member랑 Dto 구별돼야 할 거 같아서요

2023-02-04 04:58 UTC, kth990303 commented on src/main/kotlin/nexters/admin/support/exception/CustomExceptions.kt
> +package nexters.admin.support.exception
exception은 `support`보단 상위 패키지일 것 같은데 어떻게 생각하시나요?

2023-02-04 04:58 UTC, kth990303 commented on src/test/kotlin/nexters/admin/support/auth/JwtTokenProviderTest.kt
> +    }
오호 이것도 JwtException 발생 잘 하네요 👍

2023-02-04 04:58 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +        this.isInitPassword = false
음 저는 isInitPassword -> 초기화가 진행이 됐는지 여부라서 비밀번호 수정되면 true로 바뀌는 게 나아보이는데 어떻게 생각하시나요?
만약 false로 할 거라면 프로퍼티의 디폴트값은 true로 바꿔주어야 할 것 같습니다.

2023-02-04 05:05 UTC, kth990303 commented on src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
> +
오프라인으로 얘기한 결과 UserDtos 로 결정 땅땅땅

1. 아직 기능이 그리 많지 않음.
2. TokenResponse는 admin, member 모두 쓰임

2023-02-04 05:08 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/controller/user/UserDtos.kt
> +
`user`라는 패키지명에 맞춰서 일단은 UserDtos로 진행!

2023-02-04 05:14 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/support/exception/CustomExceptions.kt
> +package nexters.admin.support.exception
저도 괜찮은 것 같아요

2023-02-04 05:17 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +        this.isInitPassword = false
false => true로 수정하되, 초기화 진행 여부를 명시하기 위해 `hasChangedPassword`로 네이밍을 수정하는걸로 오프라인에서 이야기 완료!

2023-02-04 05:41 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +        val member = createNewMember()
테스트 픽스처 생성 메서드 `createNewMember`의 경우 매개변수의 디폴트 값을 다른 값으로 덮어씌울 수 있도록 설정했습니다.

2023-02-04 05:41 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +import nexters.admin.exception.NotFoundException
support 패키지에서 exception 패키지 분리 완료

2023-02-04 05:48 UTC, kth990303 approved these changes
수고하셨어요 :)

2023-02-04 05:48 UTC, kth990303 commented on src/test/kotlin/nexters/admin/Fixtures.kt
> +}
디폴트값 굳

2023-02-04 05:48 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +        this.hasChangedPassword = true
좋아요~ 👍

2023-02-04 06:32 UTC, ykc415 approved these changes

2023-02-04 06:32 UTC, ykc415 commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +            throw UnauthenticatedException.loginFail()
여기서 exception 을 trhow 하면 엔티티에서 서비스에 대한 dependency 가 생겨서 제생각에는 boolean 을리턴한다음 서비스에서 exception 을 던지는게 더 좋을것같습니다.

2023-02-04 07:28 UTC, xxeol2 requested changes

2023-02-04 07:28 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
>          @Column(name = "is_init_password", nullable = false)
얘도 `has_changed_password`로 바꿔줘야할 것 같아요!!

2023-02-04 07:52 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
>          var hasChangedPassword: Boolean = false
> 얘도 `has_changed_password`로 바꿔줘야할 것 같아요!!

완료!

2023-02-04 14:40 UTC, xxeol2 approved these changes
기나긴 수정.. 수고많으셨어요👏

2023-02-04 14:46 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +            throw UnauthenticatedException.loginFail()
저도 성현님 코멘트에 동의합니다. boolean 리턴 후 비즈니스 로직을 다루는 서비스에서 예외를 던지는게 나을 거 같아요

2023-02-05 05:44 UTC, merged

2023-02-05 05:44 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +            throw UnauthenticatedException.loginFail()
반영 완료 d44682426d360a1e40ca8f62219ecbc58137cb35