feat: 출석 정보들을 조회하는 기능 구현
Nexters/nexters-admin-server pull request #64
Opened 2023-02-25 11:53 UTC by kth990303

close #63 

테스트코드는 #60 #62 에 대한 pr이 머지돼야 추가할 수 있습니다.

2023-02-25 11:53 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +            }
`PENDING`은 결석으로 처리하지 않습니다

2023-02-25 13:08 UTC, xxeol2 requested changes
아까 응답값 정할때는 고려못했던 한가지가 떠올라서 하나만 요청할게요!
나머지는 다 좋습니당 👍

2023-02-25 13:08 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +        val name: String,
저희 출결설정 기능이 있어서 (어드민측에서 출석정보를 지각/통보결석/무단결석 등으로 설정하는 기능)
attendanceId도 같이 보내줘야할 것 같아요!

2023-02-25 13:19 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +        val name: String,
79번째 라인에 AttendanceSessionResponse에서 보내주고 있습니다!

2023-02-25 13:32 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +        val name: String,
헷갈릴것 같으면 컬럼 위치를 위로 이동할까요?

2023-02-25 13:47 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceDtos.kt
> +        val name: String,
엥 까막눈인증해버렸네 ㅋㅋㅋ

2023-02-25 14:37 UTC, xxeol2 approved these changes

2023-02-26 13:31 UTC, bugoverdose reviewed
이 PR부터 AttendanceAcceptanceTest를 구현해보는건 어떨까요

2023-02-27 12:51 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +        val generationMember = generationMemberRepository.findByIdOrNull(it.generationMemberId)
`it`도 그렇구 private 메서드 만들 때 IDE로 만들어주는걸 항상 그대로 사용하는 느낌이 좀 드는군용

2023-02-27 12:51 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/attendance/QrCodeService.kt
> +        session.updateStartAttendTime(LocalDateTime.now())
이거 이렇게 출석/QR 코드 관련 작업할 때 하지 말고, 세션에 대한 CRUD 작업에서 그냥 값을 직접 하드코딩해주자고 말했던걸로 기억하는디. 저게 그냥 어드민이 참고할려고 만드는 값이라서.

2023-02-27 12:51 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/acceptance/AcceptanceFixtures.kt
> +    }
이 파일명이 AcceptanceFixtures인게 적절한지 갑자기 의문이 드는구먼.

2023-02-27 12:55 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/attendance/QrCodeService.kt
> +        session.updateStartAttendTime(LocalDateTime.now())
예를 들어, 이 `POST /api/sessions` API의 요청/응답 DTO에 startAttendTime과 endAttendTime 필드를 추가하는 느낌?

```kotlin
    @Operation(summary = "[관리자 페이지] 세션 생성")
    @SecurityRequirement(name = "JWT")
    @PostMapping
    fun createSession(
            @RequestBody @Valid request: CreateSessionRequest,
    ): ResponseEntity<CreateSessionResponse> {
        val sessionId = sessionService.createSession(request)
        return ResponseEntity.ok(CreateSessionResponse(sessionId))
    }
```

2023-02-27 12:56 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +        val generationMember = generationMemberRepository.findByIdOrNull(it.generationMemberId)
귀신같군요 갠적으론 선호하는 편입니다.
`it`를 좋어하기도 하고, 한줄이면 중괄호 대신 등호도 괜찮다고 생각해서

2023-02-27 12:57 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/attendance/QrCodeService.kt
> +        session.updateStartAttendTime(LocalDateTime.now())
음... 기획이슈인가요?
근데 그저께 프론트랑 같이 스웨거 시뮬할 때, attendTime에 값 직접 넣어달라고 요청들어올때마다 넣는거 넘 귀찮던데

2023-02-27 12:58 UTC, kth990303 commented on src/test/kotlin/nexters/admin/acceptance/AcceptanceFixtures.kt
> +    }
저는 픽스쳐 괜찮은거같은데 좋은 네이밍 있으면 적극 추천받습니다 😀

2023-02-27 13:03 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/attendance/QrCodeService.kt
> +        session.updateStartAttendTime(LocalDateTime.now())
제가 옛날 figma를 기준으로 생각한것 같은데 한번 기획쪽에 문의해보는걸루

2023-02-27 13:04 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/attendance/AttendanceService.kt
> +        val generationMember = generationMemberRepository.findByIdOrNull(it.generationMemberId)
급하게 한게 아니라 취향인거면 패스

2023-02-27 13:08 UTC, bugoverdose approved these changes

2023-02-27 13:08 UTC, merged