feat: 관리자 관련 회원 업무 api 작성
Nexters/nexters-admin-server pull request #8
Opened 2023-02-09 12:21 UTC by kth990303

close #7  (반드시 해당 이슈를 읽어주세요. 예상치 못한 기획 및 개발 로직들을 이슈에 적어놓았습니다.)

### 회원 관련 API 생성
- Swagger PR 머지됨에 따라 이를 반영하여 `@Operation`을 간단히 적어보았습니다.
- 기수 회원과 회원이 상당히 의존성이 깊어서 (JPA 상의 N+1 외에도 기획적으로의) N+1 문제가 발생할 수 밖에 없는 듯합니다. 
- 페이지네이션은 미적용하였습니다. 이후에 회의를 해봐야할 듯합니다.

### 테스트 작성
- 통합 테스트는 BehaviorSpec을 이용한 Nested Spec 을 이용했습니다. 다만, 이러한 스펙은 테스트 작성 (시간적, 난이도적)비용이 크다는 문제점이 존재합니다. StringSpec 혹은 일반 테스트로 바꿀지 고민중입니다.
- 실제로 테스트코드는 로직에 에러가 없는지 검증하는 역할 뿐 아니라, 프로덕션 코드가 깔끔한지 확인해볼 수 있는 좋은 역할을 합니다. 따라서 시간이 매우 촉박하지 않은 한, 개인적으론 테스트 코드는 매우 중요하다고 생각하여 작성해보았습니다.
- memberServiceTest에서 repository mocking을 하지 않은 이유는 실제 회원 정보가 수정이 잘 됐는지 확인을 해야 했기 때문입니다. 만약 repository를 mocking한다면 실제로 회원 정보 및 기수가 수정됐는지 확인하기 어렵습니다. (mock 객체는 반드시 수정됐다고 안내하게 반환하도록 given으로 설정할테니 말이죠.)

### 리뷰받고 싶은 사항
- #7 에 적힌 이슈에 해당되는 개발적, 기획적 문제
- 실수로 놓친 요구사항 미반영 및 에러를 발생시킬 수 있는 로직
- 테스트 스펙

2023-02-09 12:28 UTC, kth990303 commented on build.gradle
> +	testImplementation 'io.kotest.extensions:kotest-extensions-spring:1.1.2'
kotest의 mocking을 위한 mockK (mockito보다 kotlin스러운 코드를 작성할 수 있게 해줍니다. kotlin DSL와도 혼용이 가능합니다.), kotest의 다양한 테스트 스펙을 위한 `kotest-extensions-spring`를 의존성에 추가했습니다.

2023-02-09 12:28 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
> +@Transactional
개인적으로는 `@Transactional`을 [특정 이유](https://tecoble.techcourse.co.kr/post/2020-08-31-jpa-transaction-test/)때문에 테스트 코드에서 쓰고 싶지 않은데요.

해당 어노테이션을 제거하고 `afterEach { XXXrepository.deleteAll() }` 코드를 추가하면 영속성 컨텍스트 문제 때문인진 모르겠는데 아래처럼 테스트가 깨집나다.
![image](https://user-images.githubusercontent.com/57135043/217811972-a7b8f383-72a1-4069-a81c-1a3567fc1f2e.png)
![image](https://user-images.githubusercontent.com/57135043/217812034-81c0e341-a220-4f9b-adf4-ba37cb3182cb.png)

업데이트 반영이 안되거나, 격리가 조금 덜되거나 합니다.
이해해보고 수정해보려 했지만 조금 힘들더군요.
원인이 무엇일까요..?

2023-02-09 12:28 UTC, kth990303 commented on src/main/resources/application.yml
> +      enabled: true
localhost:8080/h2-console로 띄워서 돌려볼 수 있도록!

2023-02-09 12:28 UTC, kth990303 commented on src/main/kotlin/nexters/admin/config/SwaggerConfig.kt
> +                .contact(Contact().name("springdoc 공식문서").url("https://springdoc.org/"))
컨벤션이 제 인텔리제이 IDE에선 추가로 더 띄워주던데, 제 컨벤션이 이상한건지 성현님 컨벤션에 수정이 필요한건지 잘 모르겠습니다. 전자 쪽인거 같긴 하네요..

2023-02-09 12:28 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/generation_member/Position.kt
> +    ;
Position, SubPosition이 null이 허용될 수 있어야될 것 같아요.
subPosition의 경우 디자이너는 존재하지 않기도 하고, 이전 기수들의 직군 정보가 존재하지 않을 수도 있으며, 기수 정보를 변경할 때 직군 정보를 같이 추가해서 변경하지는 않는 기획적인 문제 때문에 이와 같이 변경했습니다.

이슈를 보면 이해하는 데에 도움이 되겠네요

2023-02-09 12:28 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
> +    extensions(SpringTestExtension(SpringTestLifecycleMode.Root))
기본적으로 kotest의 Nested Spec 에서의 lifecycle은 Leaf Test이지만, 해당 문구로 Then 대신 Given끼리 테스트 격리가 되도록 변경했습니다.

참고: https://kth990303.tistory.com/374

2023-02-09 14:24 UTC, xxeol2 requested changes
이렇게 많은 양을 하루만에..!!
정말 수고 많으셨습니다 ㅋㅋㅋ
간단한 리뷰 남겨요!! 테스트코드쪽은 아직 꼼꼼하게 못봤는데 내일 시간날 때 다시한 번 확인하겠습니다!

2023-02-09 14:24 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/controller/user/MemberController.kt
>  @Tag(name = "Users", description = "유저")
Members로 통일해주면 좋을 것 같아요!

2023-02-09 14:24 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +                        })
저.. JPA를 잘 몰라서 질문하는 것 같긴 한데 ㅠ

1. `memberRepository`에서 findAll해온 `members`에서 id만 뽑아서 `memberIds`배열로 뽑아놓고,
2. `generationMemberRepository`에서 memberId가 memberIds배열에 존재하는 `generationMembers`를 뽑아오고
3. 코드상에서 `members`와 `generationMembers`를 엮어주는 방식은 어떻게 생각하시나요?!

현재 코드의 경우엔 member가 100명이라면 db에 101번(member에서 1번, generationMember에서 100번) 접근하는데, 해당 방법을 사용하면 2번만 접근하면 될 것 같아서요!

2023-02-09 14:24 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +        updateGenerateMemberInfo(updateMemberRequest, findMember)
[Clean Code - 의미있는 이름](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20%EC%9D%98%EB%AF%B8%20%EC%9E%88%EB%8A%94%20%EC%9D%B4%EB%A6%84.md)
클린코드 법칙에서 클래스 네임에는 Info, Data와 같은 불용어를 붙이는 것을 지양하는데, 메서드 네이밍에서는 어떻게 생각하시나요?!

2023-02-09 14:24 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +                .map { generationMemberRepository.deleteById(it.id) }
해당 부분에 대해서도, 위에서 말한 것과 같은 맥락으로

1. `generationMemberRepository.findAllByMemberId(findMember.id)`로 전체 기수정보를 불러와 `generationMembers`로 저장해두고
2. updateMemberRequest의 기수 정보중 `generationMembers`에 존재하지 않는 기수에 대해서 새롭게 저장하는 방법은 어떻게 생각하시나요?

db에 접근하는 횟수를 줄일 수 있을 것 같아서요!
이번 사항은 위 사항만큼은 중요하지 않은 것 같은데 (기수 정보는 아무리 많아도 몇십개일 것이기 때문) db에 접근하는 횟수는 최대한 줄이는게 좋지 않을까? 라는 생각에 여쭤봅니다!

2023-02-09 14:24 UTC, xxeol2 commented on src/main/kotlin/nexters/admin/controller/user/MemberController.kt
> +    @PutMapping("/{id}/position")
`회원 직군 수정`으로 수정해야할 것 같아요!

2023-02-09 14:51 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +        updateGenerateMemberInfo(updateMemberRequest, findMember)
회원 전체에 대한 정보를 바꾸는 로직이 아니다보니 고민 좀 했는데, 생각해보니 api 명세 자체도 `회원정보 수정`이라고 돼있어서 상관없겠네요.
반영하겠습니다~

2023-02-09 15:14 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +                        })
I/O 비용 절감에 동의합니다.

아래와 같이 로직을 바꿔보았어요.
1. Map<memberId, 해당 회원아이디에 해당되는 listOf(기수회원)> 자료구조 생성 (`groupBy` 콜렉션 함수 이용)
2. map을 순회. 이 때, findById로 member를 찾아오는 것은 낭비. 따라서 members 배열을 순차탐색하여 index를 증가시키는 방향으로 진행. (어차피 member, generationMembers 모두 memberId 순으로 저장돼있다.)

```kotlin
    @Transactional(readOnly = true)
    fun findAllByAdministrator(): FindAllMembersResponse {
        val members = memberRepository.findAll() // member는 어차피 id 순으로 저장됨
        val generationMembers = generationMemberRepository.findAll()
                .groupBy { it.memberId } // Map<memberId, listOf(GenerationMember)> 반환

        return findAllGenerationMembersByMemberId(generationMembers, members)
    }

    private fun findAllGenerationMembersByMemberId(
            generationMembers: Map<Long?, List<GenerationMember>>, members: List<Member>,
    ): FindAllMembersResponse {
        val findAllMembers: MutableList<FindMemberResponse> = mutableListOf()
        var currentMemberIndex = 0
        generationMembers.forEach {
            findAllMembers.add(FindMemberResponse.of(members[currentMemberIndex++], it.value))
        }

        return FindAllMembersResponse(findAllMembers)
    }
```

로직이 복잡하기 때문에 테스트 코드의 검증력(?) 또한 더 강화시켰습니다 ㅎㅎ

2023-02-09 15:40 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +                .map { generationMemberRepository.deleteById(it.id) }
음 DB 로직은 줄어드는 대신 애플리케이션에서의 시간복잡도가 O(NM)으로 커질 것 같긴 해서 조금 고민되긴 하네요.
커밋 이후에 findBy로 가져오는 정보들이 좀 있어서 DB로직 좀 있어도 캐싱될 거 같긴한데... 실행계획을 볼 수 없기도 하구, 말씀하신대로 기수가 많진 않아서 일단 말씀하신대로 리팩터링했습니다!

2023-02-09 16:19 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +                .map { generationMemberRepository.deleteById(it.id) }
`가독성, 애플리케이션 로직 증가 vs findBy 호출 횟수 곱증가`면으로 고민을 해보았는데, 피드백주신대로 DB 로직을 줄이도록 리팩터링 하는게 좋은 방향 같네요 ㅎㅎ
소팅, 필터링 등의 통계 관련 처리(인덱스로 이점을 보는 부분)라면 쿼리 및 DB로직이 조금 증가하더라도 애플리케이션 로직 단순화를 하겠지만, 그 외에 단순한 쿼리의 횟수 증가라면 애플리케이션 로직 리팩터링이 맞는 거 같네요.

2023-02-11 04:58 UTC, kth990303 commented on build.gradle
> +	testImplementation 'io.kotest.extensions:kotest-extensions-spring:1.1.2'
mock, spec 안쓸거라 제거했습니다

2023-02-11 04:59 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
> +    extensions(SpringTestExtension(SpringTestLifecycleMode.Root))
이 부분도 이제 사용 안합니다

사유: behaviorspec 제거

2023-02-11 05:15 UTC, bugoverdose requested changes

2023-02-11 05:15 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/service/auth/AuthServiceTest.kt
> +    val authService = AuthService(memberRepository, tokenProvider)
이거 완전 지원 플랫폼 스타일

2023-02-11 05:15 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/controller/user/MemberController.kt
> +        val findAllMembersResponse = memberService.findAllByAdministrator()
`@LoggedInAdmin` 처리해주는 ArgumentResolver 구현을 누락한거 같은디 
1. `nexters.admin.support.auth.LoginUserResolver` 참고해서 구현하거나 
2. 아니면 인터셉터로 전환하는거 어떤가요.

2023-02-11 05:38 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/auth/AuthServiceTest.kt
> +    val authService = AuthService(memberRepository, tokenProvider)
ㅋㅋ mocking 걍 빼버렸어요

2023-02-11 05:39 UTC, kth990303 commented on src/main/kotlin/nexters/admin/controller/user/MemberController.kt
> +        val findAllMembersResponse = memberService.findAllByAdministrator()
구현 @bugoverdose 에게 위임됐습니다~~ 수고하세요 ^^

2023-02-11 05:45 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/controller/user/MemberController.kt
> +        val findAllMembersResponse = memberService.findAllByAdministrator()
가슴이 웅장해진다

2023-02-11 05:54 UTC, kth990303 commented on src/test/kotlin/nexters/admin/service/auth/AuthServiceTest.kt
> +    fun `관리자 회원 로그인 시 토큰 발행`() {
관리자 로그인 PR이 머지돼서 추가로 제가 구현했습니다.
인수테스트는 아직 구현 안했습니다.

2023-02-11 07:21 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/Fixtures.kt
> +        phoneNumber: String = "010-1234-5678",
하이픈(-) 다시 지우고 전화번호에 대한 정규표현식 추가하는게 좋을 것 같아요. (0-9 몇 개짜리 문자열)

2023-02-11 07:21 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +                    generationMemberRepository.save(
구두로 설명을 들으니 잘 구현한것 같은데, 코드만 봤을 때 좀 이해하기 어려워요.

2023-02-11 07:21 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +        generationMemberRepository.save(
주석을 지우거나 javadoc으로 구현해보는건 어떨까요?

2023-02-11 07:32 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
>          this.hasChangedPassword = true
깃 충돌 해결하는 과정에서 이전 PR의 변경내역이 덮어써진 것 같아요.

2023-02-11 07:32 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/generation_member/SubPosition.kt
> +    }
굿

2023-02-11 07:42 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +                    generationMemberRepository.save(
수정완료~

2023-02-11 07:42 UTC, kth990303 commented on src/test/kotlin/nexters/admin/Fixtures.kt
> +        phoneNumber: String = "010-1234-5678",
수정완료~

2023-02-11 07:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/service/user/MemberService.kt
> +        generationMemberRepository.save(
주석 제거했습니다~

2023-02-11 07:44 UTC, kth990303 commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
>          this.hasChangedPassword = true
수정했어요~

2023-02-11 07:50 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/domain/user/member/MemberTest.kt
> +
- 제거하고 PHONE_NUMBER라는 상수를 Fixtures에 만들어 공용합시다.

2023-02-11 07:52 UTC, bugoverdose approved these changes

2023-02-11 08:43 UTC, xxeol2 approved these changes

2023-02-11 11:23 UTC, bugoverdose commented on src/main/kotlin/nexters/admin/domain/user/member/Member.kt
> +        @Embedded
admin쪽에서도 동일한 문제 password 컬럼 이슈가 있는데, 아래처럼 Password 쪽에서 해결하는건 어떨까 싶네요. 지금 PR 말고 어드민 인증 관련 PR에서 논의해봐도 좋을 것 같아요.

```kotlin
@Embeddable
data class Password(
        @Column(name = "password", nullable = false)
        var value: String
) {
```

2023-02-11 12:03 UTC, bugoverdose commented on src/test/kotlin/nexters/admin/service/user/MemberServiceTest.kt
> +    }
`ApplicationTest` 같은 클래스를 만들어서 @BeforeEach/@AfterEach에서 모든 테이블을 truncate해주는걸 구현하는게 편하지 않을까 싶네요. 

그러면 아래처럼만 해도 될 것 같아요.

```kotlin
class MemberServiceTest(
        @Autowired private val memberService: MemberService,
) : ApplicationTest {
```

2023-02-12 05:53 UTC, ykc415 approved these changes

2023-02-12 05:53 UTC, ykc415 commented on src/main/kotlin/nexters/admin/config/SwaggerConfig.kt
> +                .contact(Contact().name("springdoc 공식문서").url("https://springdoc.org/"))
코드 인텔리제이 디폴트 사용하게되있는데 이상하네요 ;

2023-02-12 05:57 UTC, merged